apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coweave-website

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: coweave-website
  app.kubernetes.io/component: website
  app.kubernetes.io/part-of: coweave
